name: Upload Merged Plugin

on:
  pull_request:
    types: [closed]
    branches: 
      - main
      - dev
    paths-ignore:
      - "migrations/**"
      - ".scripts/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE"

env:
  REPO_NAME: langgenius/dify-official-plugins

jobs:
  upload-merged-plugin:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download Plugin Daemon
        env:
          GH_TOKEN: ${{ secrets.ORG_SCOPE_GITHUB_TOKEN }}
        run: |
          gh release download -R langgenius/dify-plugin-daemon --pattern "dify-plugin-linux-amd64" --dir .scripts
          chmod +x .scripts/dify-plugin-linux-amd64

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get PR Path
        env:
          GH_TOKEN: ${{ secrets.ORG_SCOPE_GITHUB_TOKEN }}
        run: |
          export PR_FILES=$(gh pr view -R ${{ env.REPO_NAME }} ${{ github.event.pull_request.number }} --json files --jq .files)

          if PLUGIN_PATH=$(python3 .scripts/check-prefix.py); then
              echo $PLUGIN_PATH
              echo "PLUGIN_PATH=$PLUGIN_PATH" >> $GITHUB_ENV
          else
            echo "PR files cross different plugin directories, skip upload."
            exit 1
          fi

      - name: Check Plugin Deps
        run: |
          if [ -f ${{ env.PLUGIN_PATH }}/requirements.txt ]; then
            echo "Trying to install plugin dependencies..."
            python3 -m venv .venv
            source .venv/bin/activate
            python3 -m pip install -r ${{ env.PLUGIN_PATH }}/requirements.txt
            deactivate
          fi

      - name: Upload Plugin
        if: env.PLUGIN_PATH != ''
        run: |
          python3 .scripts/upload-package.py -d ${{ env.PLUGIN_PATH }} -t ${{ secrets.MARKETPLACE_TOKEN }} --plugin-daemon-path .scripts/dify-plugin-linux-amd64 -u ${{ secrets.MARKETPLACE_BASE_URL }} -f
